### ISSUE TITLE
Optimized for Mobile View

### ISSUE THREAD

**Issue by HendryTju** [codescapes-io/codescapes-io.github.io#12]
Design currently not yet optimized for mobile view.

### Reproduce
1. Go to Chrome -> open website
2. Click on console -> click toggle device toolbar
3. Result: should looks good on mobile view

### Current
looks skewed to the left 🤔

![image](https://user-images.githubusercontent.com/39986552/151733237-5deb6058-5974-437b-adab-5a66cc645589.png)

**Comment by rennols** [comment]
can you attach figma link for this frame?

**Comment by HendryTju** [comment]
https://www.figma.com/file/zbrBIPsOJGzDfpev6ewhBV/Website-Codescapes.io?node-id=0%3A1
@rennols , please check this figma ya. We create new one because its really slow on the old one.

**Comment by rennols** [comment]
if possible please share link of specific frame related this task
Is this frame is for this task? https://www.figma.com/file/zbrBIPsOJGzDfpev6ewhBV/Website-Codescapes.io?node-id=17%3A12
